---
name: Lint

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - master

jobs:
  superlinter:
    name: Superlinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GENERATED_FILES: true
          FILTER_REGEX_EXCLUDE: '.*SUMMARY.md'
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_EDITORCONFIG: false
          MARKDOWN_CONFIG_FILE: '.markdownlint.json'
  mdformat:
    name: Markdown Formatting
    runs-on: ubuntu-latest
    container:
      image: docker.io/python:slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mdformat
        run: |
          pip install mdformat
          mdformat --check --wrap no --number ./**/*.md
